#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'Plim==0.9.12','console_scripts','plimc'
__requires__ = 'Plim==0.9.12'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('Plim==0.9.12', 'console_scripts', 'plimc')()
    )
